Allow locker to run under fresh install.
I was getting errors like this without this change:
=========
8 Sep 12:36:13 - info: spawning into: /home/bewest/Documents/git/Locker/Me/dashboardv3
[dashboardv3] The "sys" module is now called "util". It should have a similar interface.
[dashboardv3] <Buffer 65 78 65 63 76 70 28 29 3a 20 4e 6f 20 73 75 63 68 20 66 69 6c 65 20 6f 72 20 64 69 72 65 63 74 6f 72 79 0a>
[dashboardv3]
[dashboardv3] node.js:201
        throw e; // process.nextTick error, or 'error' event on first tick
              ^
[dashboardv3] Error: Cannot find module 'connect-form'
    at Function._resolveFilename (module.js:332:11)
    at Function._load (module.js:279:25)
    at Module.require (module.js:354:17)
    at require (module.js:370:17)
    at Object.<anonymous> (/home/bewest/Documents/git/Locker/Apps/dashboardv3/dashboard-client.js:20:12)
    at Module._compile (module.js:441:26)
    at Object..js (module.js:459:10)
    at Module.load (module.js:348:31)
    at Function._load (module.js:308:12)
    at Module.require (module.js:354:17)
8 Sep 12:36:13 - info: dashboardv3 exited with status 1, signal null
8 Sep 12:42:33 - info: Having to spawn dashboardv3
8 Sep 12:42:33 - info: spawning into: /home/bewest/Documents/git/Locker/Me/dashboardv3
[dashboardv3] The "sys" module is now called "util". It should have a similar interface.
[dashboardv3] <Buffer 65 78 65 63 76 70 28 29 3a 20 4e 6f 20 73 75 63 68 20 66 69 6c 65 20 6f 72 20 64 69 72 65 63 74 6f 72 79 0a>
8 Sep 12:42:33 - info: Set local uri to http://localhost:48952/ for dashboardv3